# Cross compile to Android 32-bit using NDK standalone toolchain

set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_PROCESSOR armv7-a)
set(CMAKE_ANDROID_ARM_NEON "ON")

if(NOT DEFINED ENV{ANDROID_TOOLCHAIN_32})
  message(FATAL_ERROR "Environment variable ANDROID_TOOLCHAIN_32 not set")
endif()
set(CMAKE_ANDROID_STANDALONE_TOOLCHAIN $ENV{ANDROID_TOOLCHAIN_32})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
